### ISSUE TITLE
Semantics of Either are inverted

### ISSUE THREAD

**Issue by contrasam** [bwireman/gleither#1]
Hey @bwireman ,

I was looking into the library, the semantics of Either is the Left holds the error and Right holds the success result, i bring it up because people from other languages are used to this convention and could be confusing at time.

I am from kotlin and for instance in arrow its like this https://apidocs.arrow-kt.io/arrow-core/arrow.core/-either/index.html

**Comment by bwireman** [comment]
Shoot, you're totally right. Haven't used one in a while, I'll swap that around!

**Comment by bwireman** [comment]
Pushed here: https://github.com/bwireman/gleither/commit/12958605625fdb83d01eac7aa9115411d6a3b098

Will do some cleanup before publishing
